@startuml Si



class Fifa
class Personas
class Jugador
class Balon
class Portero
class Porteria
class Ventana
class Actualizable
class Dibujo
class Juegos 

Personas o-- Juegos
Fifa --|> Juegos
Fifa *-- Jugador
Fifa *-- Porteria
Fifa *-- Portero
Fifa *-- Balon
Fifa o-- Ventana
Fifa o-- Dibujo
Fifa o-- Actualizable
Portero o-- Porteria
Jugador o-- Balon

@enduml