@startuml

class Fifa {
    + iniciarPartido()
    + finalizarPartido()
    + pausarPartido()
}

class Personas {
    + agregarPersona()
    + eliminarPersona()
}

class Jugador {
    + correr()
    + patear()
    + pasar()
    + defender()
}

class Balon {
    + mover()
    + detener()
}

class Portero {
    + atajar()
    + despejar()
}

class Porteria {
    + registrarGol()
}

class Ventana {
    + abrir()
    + cerrar()
}

class Actualizable {
    + actualizar()
}

class Dibujo {
    + dibujar()
    + borrar()
}

class Juego {
    + iniciar()
    + detener()
    + reiniciar()
}

Personas o-- "1" Juego
Fifa --|> "1" Juego
Fifa *-- "11" Jugador
Fifa *-- "2" Porteria
Fifa *-- "1" Portero
Fifa *-- "1" Balon
Fifa o-- "1" Ventana
Fifa o-- "1" Dibujo
Fifa o-- "1" Actualizable
Portero o-- "1" Porteria
Jugador o-- "1" Balon

@enduml
